[package]
name = "heighway_dragon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
turtle = {git = "https://github.com/sunjay/turtle"}


#[profile.dev.package."*"]
#opt-level = 3
